version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql.${COMPOSE_PROJECT_NAME}.docker
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ~/data/${DATABASE_NAME}.docker:/var/lib/mysql
        ports:
            - ${DATABASE_PORT}:3306
        networks:
            - global

networks:
    global:
        external: true
